extract:
  extract_type: limesurvey_extract
  tables:
    - lime_group_l10ns
    - lime_questions
    - lime_question_l10ns
    - lime_survey_977429

transformation_pipelines:
  - table_name: question_groups
    staging_schema: staging
    columns:
      - name: question_group_id
        type: INTEGER
        primary_key: True
        nullable: False
      - name: question_group_name
        type: VARCHAR(255)
      - name: description
        type: VARCHAR(255)
        nullable: True
    source_data:
      source_tables:
        - table_name: lime_group_l10ns
          columns:
            - gid AS question_group_id
            - group_name AS question_group_name
            - description
      source_schema: raw

    transform_steps:
      - transform_type: rename_columns
        colname_to_colname:
          gid: question_group_id
          group_name: question_group_name

  - table_name: question_items
    staging_schema: staging
    columns:
      - name: question_item_id
        type: INTEGER
        primary_key: True
        nullable: False
      - name: question_item_title
        type: VARCHAR(255)
        nullable: True
      - name: question_group_id
        type: INTEGER
        nullable: False
        foreign_key: "staging.question_groups.question_group_id"
      - name: type_major
        type: VARCHAR(255)
        nullable: True
      - name: type_minor
        type: VARCHAR(255)
        nullable: True
    source_data:
      source_tables:
        - table_name: lime_questions
          columns:
            - qid AS question_item_id
            - title AS question_item_title
            - gid AS question_group_id
            - type AS type_major
            - type AS type_minor
      source_schema: raw
    transform_steps:
      - transform_type: join_with_csv_mapping
        mapping_path: airflow/include/mappings/Mapping_LS-QuestionTypesMajor.csv
        mapping_delimiter: ;
        keep_columns:
          - "Fragetyp Major (CFE)"
        left_on: type_major
        right_on: "Fragetyp-ID (LS)"
        how: left
      - transform_type: rename_columns
        colname_to_colname:
          "Fragetyp Major (CFE)": type_major

  - table_name: subquestions
    staging_schema: staging
    columns:
      - name: subquestion_id
        type: INTEGER
        primary_key: True
        nullable: False
      - name: question_item_id
        type: INTEGER
        nullable: False
        foreign_key: staging.question_items.question_item_id
      - name: subquestion_item_title
        type: VARCHAR(50)
      - name: question_item_title
        type: VARCHAR(50)
    source_data:
      source_tables:
        - table_name: lime_questions
          columns:
            - qid AS subquestion_id
            - title AS subquestion_item_title
        - table_name: lime_questions
          columns:
            - qid AS question_item_id
            - title AS question_item_title
      source_schema: raw
      join:
        type: JOIN
        left_table: lime_questions
        right_table: lime_questions
        left_on: parent_qid
        right_on: qid
      filter: "WHERE left_table.parent_qid != 0"
    transform_steps:
      - transform_type: add_computed_column
        column_name: subquestion_item_title
        input_columns:
          - question_item_title
          - subquestion_item_title
        operator:
          name: concat
          separator: "_"

  - table_name: respondents
    staging_schema: staging
    columns:
      - name: respondent_id
        type: INTEGER
        primary_key: True
        nullable: False
    source_data:
      source_schema: raw
      source_tables:
        - table_name: lime_survey_977429
          columns:
            - id AS respondent_id

  - table_name: diversity_items
    staging_schema: staging
    columns:
      - name: diversity_item_id
        type: VARCHAR(255)
        primary_key: True
      - name: diversity_group_id
        type: VARCHAR(255)
        nullable: True
      - name: type_major
        type: VARCHAR(10000)
        nullable: True
      - name: type_minor
        type: VARCHAR(255)
        nullable: True

  - table_name: question_items_dict
    staging_schema: staging
    columns:
      - name: question_item_id
        type: INTEGER
        nullable: False
        primary_key: True
        foreign_key: "staging.question_items.question_item_id"
      - name: lang
        type: VARCHAR(2)
        primary_key: True
        nullable: False
      - name: question_item_title
        type: VARCHAR(255)
        nullable: True
      - name: label_major
        type: VARCHAR(10000)
        nullable: True
      - name: label_major_short
        type: VARCHAR(255)
        nullable: True
      - name: label_minor
        type: VARCHAR(255)
        nullable: True
    source_data:
      source_schema: raw
      source_tables:
        - table_name: lime_questions
          columns:
            - qid AS question_item_id
            - title AS question_item_title
        - table_name: lime_question_l10ns
          columns:
            - language AS lang
      join:
        type: "LEFT JOIN"
        left_table: lime_questions
        right_table: lime_question_l10ns
        left_on: qid
        right_on: qid
      filter: "WHERE left_table.parent_qid = 0"
    transform_steps:
      - transform_type: join_with_csv_mapping
        mapping_path: "airflow/include/mappings/mapping_question_items.csv"
        mapping_delimiter: ","
        keep_columns:
          - label_major
          - label_minor
        left_on: question_item_title
        right_on: question_item_id
        how: left

  - table_name: subquestions_dict
    staging_schema: staging
    columns:
      - name: subquestion_id
        type: INTEGER
        nullable: False
        primary_key: True
        foreign_key: "staging.subquestions.subquestion_id"
      - name: question_item_id
        type: INTEGER
        nullable: False
      - name: subquestion_item_title
        type: VARCHAR(255)
      - name: question_item_title
        type: VARCHAR(255)
      - name: subquestion_id_minor
        type: VARCHAR(50)
        nullable: True
      - name: lang
        type: VARCHAR(2)
        primary_key: True
      - name: label_major
        type: VARCHAR(255)
        nullable: True
      - name: label_minor
        type: VARCHAR(255)
        nullable: True
    source_data:
      source_schema: staging
      source_tables:
        - table_name: subquestions
          columns:
            - subquestion_id
            - question_item_id
            - subquestion_item_title
            - question_item_title
    transform_steps:
      - transform_type: join_with_csv_mapping
        mapping_path: "airflow/include/mappings/mapping_subquestions.csv"
        mapping_delimiter: ","
        keep_columns:
          - label_major
          - label_minor
          - lang
          - subquestion_id_minor
        left_on: subquestion_item_title
        right_on: subquestion_id
        how: left

  - table_name: question_answers_dict
    staging_schema: staging
    columns:
      - name: question_item_id
        type: INTEGER
        nullable: False
        primary_key: True
        foreign_key: "staging.question_items.question_item_id"
      - name: question_item_title
        type: VARCHAR(255)
        nullable: False
      - name: lang
        type: VARCHAR(2)
        nullable: False
        primary_key: True
      - name: answer_id
        type: VARCHAR(50)
        nullable: False
        primary_key: True
      - name: answer_text
        type: VARCHAR(10000)
        nullable: True
    source_data:
      source_schema: staging
      source_tables:
        - table_name: question_items
          columns:
            - question_item_id
            - question_item_title
    transform_steps:
      - transform_type: join_with_csv_mapping
        mapping_path: airflow/include/mappings/mapping_question_answers.csv
        mapping_delimiter: ","
        keep_columns:
          - lang
          - answer_id
          - label
        left_on: question_item_title
        right_on: question_item_id
      - transform_type: rename_columns
        colname_to_colname:
          label: answer_text
      - transform_type: fill_null_values
        column_name: lang
        value: "99"

  - table_name: diversity_items_dict
    staging_schema: staging
    columns:
      - name: diversity_item_id
        type: VARCHAR(255)
        primary_key: True
      - name: lang
        type: VARCHAR(2)
      - name: label_log
        type: VARCHAR(10000)
        nullable: True
    source_data:
      source_schema: staging
      source_tables:
        - table_name: diversity_items
          columns:
            - diversity_item_id
    transform_steps:
      - transform_type: join_with_csv_mapping
        mapping_path: airflow/include/mappings/mapping_diversity_items.csv
        mapping_delimiter: ","
        keep_columns:
          - lang
          - label_long
        left_on: diversity_item_id
        right_on: diversity_item_id

load:
  load_type: reporting_db_load
  staging_schema: staging
  target_schema: reporting
  tables:
    - question_groups
    - question_items
    - subquestions
    - respondents
    - diversity_items
    - question_items_dict
    - subquestions_dict
    - question_answers_dict
    - diversity_items_dict
