diversity_items:
  reporting_table_name: diversity_items
  columns:
    diversity_item_id:
      type: VARCHAR(255)
      primary_key: True
      nullable: False
    diversity_group_id:
      type: VARCHAR(255)
      nullable: True
    type_major:
      type: VARCHAR(10000)
      nullable: True
    type_minor:
      type: VARCHAR(255)
      nullable: True
