question_items_dict:
  reporting_table_name: question_items_dict
  columns:
    question_item_id:
      type: VARCHAR(50)
      nullable: False
      primary_key: True
      foreign_key: "reporting.question_items.question_item_id"
    lang:
      type: VARCHAR(2)
      primary_key: True
      nullable: False
    label_major:
      type: VARCHAR(10000)
      nullable: True
    label_major_short:
      type: VARCHAR(255)
      nullable: True
    label_minor:
      type: VARCHAR(255)
      nullable: True
  sql_stmt: >
    SELECT DISTINCT
      lq.title AS question_item_id
      , lqln.language as lang
    FROM raw.lime_questions lq
    LEFT JOIN raw.lime_question_l10ns lqln
    ON lq.qid = lqln.qid
    WHERE lq.parent_qid = 0;
  mapping_path: "include/mappings/mapping_question_items.csv"
  mapping_join_on: question_item_id
  empty_columns_to_add:
    - label_major_short
  target_cols:
    - question_item_id
    - lang
    - label_major
    - label_major_short
    - label_minor
  mapping_log_file_name: mapping_question_items_dict.csv

subquestions_dict:
  reporting_table_name: subquestions_dict
  columns:
    subquestion_id:
      type: VARCHAR(50)
      nullable: False
      primary_key: True
      foreign_key: "reporting.subquestions.subquestion_id"
    question_item_id:
      type: VARCHAR(50)
      nullable: False
    subquestion_id_minor:
      type: VARCHAR(50)
      nullable: True
    lang:
      type: VARCHAR(2)
      nullable: False
      primary_key: True
    label_major:
      type: VARCHAR(10000)
      nullable: True
    label_minor:
      type: VARCHAR(255)
      nullable: True
  mapping_path: "include/mappings/mapping_subquestions.csv"
  mapping_join_on: subquestion_id
  sql_stmt: >
    SELECT DISTINCT
      subquestion_id
      , question_item_id
    FROM reporting.subquestions;

question_answers_dict:
  reporting_table_name: question_answers_dict
  columns:
    question_item_id:
      type: VARCHAR(50)
      nullable: False
      primary_key: True
      foreign_key: "reporting.question_items.question_item_id"
    lang:
      type: VARCHAR(2)
      nullable: False
      primary_key: True
    answer_id:
      type: VARCHAR(50)
      nullable: False
      primary_key: True
    answer_text:
      type: VARCHAR(10000)
      nullable: True
  mapping_path: "include/mappings/mapping_question_answers.csv"
  mapping_join_on: question_item_id
  sql_stmt: >
    SELECT DISTINCT
      question_item_id
    FROM reporting.question_items;
  target_cols:
    - question_item_id
    - lang
    - answer_id
    - label AS answer_text

diversity_items_dict:
  reporting_table_name: diversity_items_dict
  columns:
    diversity_item_id:
      type: VARCHAR(255)
      primary_key: True
    lang:
      type: VARCHAR(2)
      primary_key: True
    label_long:
      type: VARCHAR(10000)
      nullable: True
  mapping_path: "include/mappings/mapping_diversity_items.csv"
  mapping_join_on: diversity_item_id
  sql_stmt: >
    SELECT DISTINCT
      diversity_item_id
    FROM reporting.diversity_items;
  target_cols:
    - diversity_item_id
    - lang
    - label_long
