name: Check resources


on:
  push:
    branches:
      - 'chore/cleanup_repo'
  pull_request:
    types: [ opened, reopened, synchronize ]

  workflow_dispatch:

jobs:
  check_syntax:
    name: Check Syntax
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'
          cache: 'pipenv'
      - name: Create and start virtual environment
        run: |
          python -m pip install pipenv
          pipenv install --dev --ignore-pipfile
      - name: Run black formatting check
        run: |
          pipenv run black --check dags plugins tests include --config ./pyproject.toml
      - name: Run isort formatting check
        run: |
          pipenv run isort --check dags plugins include tests
        if: always()
